package ba.edu.ssst;

public class Dog extends Mammal {
  Dog(String name,String breed) {
      super.name = name;
      super.breed = breed;
  }

  @Override
    public String showPicture() {
      return "MMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMMNxox0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMWklxxoxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMXdokkdookNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMOlxkkxddooKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMklxxxkxdoolkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMWxlxxxxdxololdXMMMMMMMMMMW0kxxkkOKWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMWxoxddddodlldcoXMMMMMMMWKdooodkxooxO0KXNWMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMWkodoooolllcoxccKMMMWMW0odxdc;dkdddoloodokNMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMOddllllcccclxxclKMWWWKdxkl;,'cxxdddooooclKMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMKxolcc::::;lxdc;ckkxooxkxl;;,'lxxddoooolOWMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMWkol:;;;;,:oddddONXOxxkkkdol:,'cdxdooolOWMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMMOoo;''',:dkkkxONN0kxlccoxkxoc,';odddloKMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMMklxdlcclxkkkdxXWXOdlcc:,:cokdc:c::ldooOWMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMMNkooddodkkxdoOWWKxoc;;;;;,:dkxxx::xxocxNMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMMMMXOdlcdxoocdNMW0d::odloc;;lkkkoc0MWXKNWMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMMMMMMMkcol:,;kWWWKo,xO;.ckx::kkkloNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMMMMMMWo;loooxKNNWW0dxk:',,,':kkklxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMMMMWNOc;;:cloxxONMMMWXK0xc;,lkkkoxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMMMWNOx:   ..';::kMMMMWWWMWWNXXX0oOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMMMWKd0O,     .'oXMMMMWK0WMMMMWNxdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMMMWKoOMXx;...cOWMMMMMKokWMMWMWkdKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMMMMWko0WMNOxXWMMMMWNk;cXMWMWXkkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMMMMMW0xkOOO0OO0K0ko,.;KWWKOOOKWMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMMMMMMWWXOkxdoc:;.  'dXMNO:.lNMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMMMMMMWKxdlcodxdxxdkXMMW0x:.oNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMMMMMMKddxodkxxkkONWWWWXOko::l0WWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMMMMMMOlxxddkkkO0xxXMWWKkkkx:.,kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMMMMMMOldxddxxkOKO:xMMWXko:;,,,,lkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMMMMMMXocxkxdkOKKo;OWXOo:;;::;,:::clkXWMMWMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMMMMMMWXxllloxxdc,cdl::;::;;:ldxxdoc::xXMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMMMMMMMMMX0kxd;..,,;;::clx0KK0kkkkkxxo:ckNMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMMMMMMMMMWWWMMKl:loodk0XWMMMWWNK0OOkkkko;lXMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMMMMMMMWMXkkkO0kkXWWWMMMMMMWMN0OO0XXKKK0x;:0MMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMMMMMMMWOcdKXKOoxXXNWMMMMMXOxoxkxxxxONWWN0::0MMMMMMMWWMMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMMMMMMMNloWMWWWO0W0xKMMMMNl.c0NWMMW0xdkNMWXccXMMMMMMK0WMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMMMMMMMWodWWWWNk0MNxOMMMM0c;okOKWMMMMXkkKWM0:oWMMMMMO:dNMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMMMMMMMMOxXNXNKxKMWkOMMMW0l;okkkKWMMMMMXOKWMx:0MMMMM0ockWMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMMMMMMMMNOkKXXOkNMNxOMMMWNd,lkkkONMMMWMMWXXMXcdWMMMMkxdlKMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMMMMMMMMMNOxKKx0WM0d0MMWWNo.,okk0NWMMMMMMWMMWdlNMMMXdOk:0MMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMMMMMMMMMMW0kdxNMWxxNMMWNd.  ,d0XWMMMMMNXNMMMkl0MWKodNdcKMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMMMMMMMMMMMM0d0MWOdKMMMNd.....,OWMMMMMMNKOKNW0dkOd::kk:dWMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMMMMMWKkkxk0kkKXOoxNWMWk'......'oKWMMMMMMNOk0Kl,,;cc;'oNWMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMMMMW0xkxk0NOdddll0KNWK:.;;.;:,:lokKNWMMMMMKdxo:cc;;ckNMMMMMMMMMMMM\n" +
              "MMMMMMMMMMMMMMMMMNkdOkOWNkdxxx0MWNNx.:xxkkx0WMWNXNWMMMMMMKl:;,;cxXNNWWWWMMMMMMMM\n" +
              "MMMMMMMMMMMMMMWWNXOddookdodOxxWWWWXd.cdkXxxWMMMMMMWMMWNNNOc;clxkOO00KXXNWWMMMMMM\n" +
              "MMMMMMMMMMMMMMMWWWNNXK00OkddooO0OOkdoocldcoXWNK00KK0OkkOOxk0KKKKXXXNNNWWWMMMMMMM\n" +
              "MMMMMMMMMMMMMMMMMMMMMMMMMMWNNK0KXNNWWNX00kxk000K000O0NMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMWNXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMWNXKK0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MWN0kO000XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MNKOkxxO0XNWWWWWWWWWWWMWNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMWWNXKKNNXNNXNNXXXXXXXK0XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMNXWMMMWWWWWWWWWNNXXXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
              "MMMMMNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM";
  }

  @Override
    public String makeSound() {
      return "Woof!";
  }
}
