package ba.edu.ssst;

public class Iguana extends Reptile {
    Iguana(String name,Boolean dangerous) {
        super.name = name;
        super.dangerous = dangerous;
    }

    @Override
    public String showPicture() {
        return "WWWWWWWWWWWWWWWWWWWWWX0kk0NNXKKKKXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "WWWWWWWWWWWWWWWWWWWWWkoddddoldxolkNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "WWWWWWWWWWWWWWWWWWWWKx0KdOkckXOxkdkNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "WWWWWWWWWWWWWWWWWNK0dldxddlcOXkdKOlxKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "WWWWWWWWWWWWWWWNOdllllllllllldkkxoxxdx0NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "WWWWWWWWWWWWWWWKlcloollollooolllllokOxdxkk0XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "WWWWWWWWWWWWWWWWXOxlcllllllllllllllodxxxxdddd0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "WWWWWWWWWWWWWWWWWWWKxlcllllllllollolccdkkOOOOKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "WWWWWWWWWWWWWWWWWWWWNkddollllllolllllodkOKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "WWWWWWWWWWWWWWWWWWWKdco0KdodolllllllloxxddkXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "WWWWWWWWWWWWWWWWWWNxlocdkxOKOolollllllok0OxxOXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "WWWWWWWWWWWWWWWWWWKocolloOKK0dlollllloldxkOOxxKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "WWWWWWWWWWWWWWWWWWNxllllx0KKOoloollllollooooxodXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "WWWWWWWWWWWWWWWWWWWNklcoOKKKOolollllllollodox0KNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "WWWWWWWWWWWWWWWWWWWWW0oxKKKKOollllclollooldkdOWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "WWWWWWWWWWWWWWWWWWWWWKxkKKKKOololcllllloolokkdOWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "WWWWWWWWWWWWWWWWWWWWW0d0KKKK0dlccloolllllllxOxdKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "WWWWWWWWWWWWWWWWWWWWW0x0KKKK0xlcclllllloolldOOdxNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "WWWWWWWWWWWWWWWWWWWWW0x0KKKKKkllllllloolllllloxdOWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "WWWWWWWWWWWWWWWWWWWWW0x0KKKKKOololooloollolclcoxOWWWWWWWNXNNWWWWWWWWWWWWWWWWWWWW\n" +
                "WWWWWWWWWWWWWWWWWWWWMKdOKKKKKKxlloloolollolclddkXWWWWWKxooodxONWWWWWWWWWWWWWWWWW\n" +
                "WWWWWWWWWWWWWWWWWWWWWWkx0KKKKKOdloollloooollllodxkKNWNd:cllllcdKWWWWWWWWWWWWWWWW\n" +
                "WWWWWWWWWWWWWWWWWWWWWW0lxKKKKKKkllolloollolclllodxxkOK0xxkxllocdXWWWWWWWWWWWWWWW\n" +
                "WWWWWWWWWWWWWWWWWWWWWWxcldO0KKK0xllolllllolclllllodxdldO0xlcloll0WWWWWWWWWWWWWWW\n" +
                "WWWWWWWWWWWWWWWWWWWWWXocolloxkOOkdclollllolclollolllc:cloolloocoXMWWWWWWWWWWWWWW\n" +
                "WWWWWWWWWWWWWWWWWWWWWOllolllkKXXXNOlllollolcllclooloolllllollcdKWWWWWWWWWWWWWWWW\n" +
                "WWWWWWWWWWWWWWWWWWWWKocolld0WWWWWWW0oclllocdKKOkdolcllllcclox0NWWWWWWWWWWWWWWWWW\n" +
                "WWWWWWWWWWWWWWWWWWWWOccox0NWWWWWWWWWKdcloocxNWWWNX00OOOOO0KNWWWWWWWWWWWWWWWWWWWW\n" +
                "WWWWWWWWWWWWWWWWWWWWN00XWWWWWWWWWWWWWNOdooxXWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "WWWWWMWWWMWWWWWWMWWWWWWMWWWWWWMWWWWWWWWNXXWWWMWWWMWWMWWWMWWWMWWMWWWWWWMWWWMWWWWW";
    }

    @Override
    public String makeSound() {
        return "Wheeze!";
    }
}
