package ba.edu.ssst;

public class Snake extends Reptile {
    Snake(String name, Boolean dangerous) {
        super.name = name;
        super.dangerous = dangerous;
    }

    @Override
    public String showPicture() {
        return "MMMMMMMMMMMMMMMMWMWN0OkxdooooddxkO0XWWWWMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMMWNX0kxddoooododddoddoxKXKNMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMW0xoooddoollllodddddddd0KocokXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMNxlddddddodkOxoodddddddxXx'..c0WWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMNOkOooddlxNKxxkoodddooodK0c;lk0OKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMMWXklcdddoxKk::dkkOOkxl:lOX000OxddONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMWWWXkddddddodddkKXNNNNXdcccoddoddddOKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMWNNNNKkddddddddddOXXKXNNNX000o:clldddkXkl0MWMMWMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMWXXNXXXOxdddddddx0XOx0XXXK0KXKKOl::loxKO;.cXWWMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMNXXNNNXXKOddddxOKOooOKKKKXNWWXXXOxo;lOX0dlckWMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMWNXKXN0x0XK00K0kl:oOKKNWWMMWWWXKXN0l:lxkO0OOXMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMWNXKKK00KK0xl;'ck0KNWWMMMMMWMWXXXKx::oddddd0WWMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMWWX0Oxlol..:kKKXWMMMMMMMMMMMNXXXOc;lddddd0WMWWMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMMMWXkllloxOKKXWMMMMMMMMMMMMMNXXX0l;ldddOKKNMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMMWWWKoo0XXXXXNWMMMMMMMMMMMMMMNXXXkc:oxOK0oxNMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMMWWNOdo0WWWMMMMMMMMMMMMMMMMMMWNXNXk::xXXx,.dWMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMWN0xodOXWMMMMMMMMMMMMMMMMMMMMMWXKKOo:cokK0o,xMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMNkllkNWWMMMMMMMMMMMMMMMMMMMMMMNXNXk::ldddOK0KMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMKdll0WWMMMMMMMMMMMMMMMMMMMMMMWXK0Oo;coddddx0NWMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMWKdlcxNMMMMMMMMMMMMMMMMMMMMMMWNKKdc::ldxOKKk0WMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMWWX0xdkol0WMMMMMMMMMMMMMMMMMMMMMNXX0l;:dO0OdlkKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMWNK0KNKxxXMMMMMMMMMMMMMMMMMMMMMWXKOl::l0Nx'..;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMWWMMWNNWWWMMMMMMMMMMMMMMMMMMWWNXKd:lodkKK:..dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMWMMMWWWMMMMMMMMMMMMMMMMMMMMMMNKOdclddddOXKdxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMMMMWXXXK0KKkdkKXKXNNWWWMMMMNXOlcodddddxkOKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "WWMMWXko:,dKkodOxcdOxookOolkKNWWKxllodddddddoxXMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMM\n" +
                "WWNK0OxdolOKxddoxkxoloddOxodxxkkddkOOO0KKKKkkXWMMMMWWWNK0OKKk0K0KNWMMMMMMMMMMMMM\n" +
                "WNKOkxxkOO0koodoodoolccclxxdoolloOXKdllcco0KNWMMWWXkOKkoolokkxoookKKNMMMMMMMMMMM\n" +
                "XOxoxkO0kdoox0KKKXXKK0Oxol:clodddxXk'.....,lOX0OkkOkOkoloodxkxdoooxkk0XNWMMMWWNX\n" +
                "0k;..:0NKxx0XXXXNNNNNXK00OdddddddxKKc'.;loclOOddolllodxOKXXNNNXXKOkkxoodkOOkkdoo\n" +
                "OkxdkKKkdodxOKKXNXXK0OxOK0000kxdddOK0kccodkxlcclloxk0XXNWWMMMMWWWNNNX0kxdddddxOK\n" +
                "OoccoxdddxOkd:':kOddodkXk,,coOK0xooox0OkkkkxxkOO0XXXNWWMMMMMMMMMMMMMWWWNNNNNNWMW\n" +
                "Kkl::clookKd....lKkddkXO;....cK0ookKNNXNNNXXXNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "NK0xc:::cldOo,;oOOxddx00koc,;OKkOXWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "WNNKOkdl:;;lxkxdollllllloxOO0XXNMMWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMWNXX0kkxddoccccccccldxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "MMMMMWWNXXXXK0OOOkOO0KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM";
    }

    @Override
    public String makeSound() {
        return "Pssss";
    }
}
